name: flutter_aira
description: The Aira Flutter SDK.
version: 0.0.1
homepage: https://github.com/aira-collab/flutter_aira

environment:
  flutter: ">=1.17.0"
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  device_info_plus: ^3.2.2
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.8.4
  http: ^0.13.4
  logging: ^1.0.2
  mqtt_client: ^9.6.5
  package_info_plus: ^1.4.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
