name: flutter_aira
description: The Aira Flutter SDK.
version: 0.0.25
homepage: https://github.com/aira-collab/flutter_aira

environment:
  flutter: ">=3.0.0"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  android_id: ^0.0.4
  device_info_plus: ^4.0.2
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.6
  http: ^0.13.4
  logging: ^1.0.2
  mqtt_client: ^9.6.8
  package_info_plus: ^1.4.3
  pubnub: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  web:
