name: "Install dependencies"
description: Install dep
inputs:
  private-key:
    required: true
    description: "SSH private key"


runs:
  using: "composite"
  steps:
    - name: set variables
      shell: bash
      run: |
        git config --global core.compression 0

    - name: Add ssh key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.private-key }}

    - name: Setup Flutter
      id: flutter-step
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml
        cache: true

    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
